# Introduction

The UVX BRT system is a fairly new transit network in Utah County. This system makes use of traffic signal prioritization (TSP) not to maintain a set schedule of arrivals and departures, but rather to achieve consistent headways, or times between the arrivals of buses. The use of TSP has been used for a variety of purposes, but the combination of TSP with metrics of headway deviation is a newer application of TSP. In 2019 the new UVX system provided its services under four separate TSP strategies throughout the year, including a five minute threshold for priority, a two minute threshold for priority, an unconditional priority, and no priority. Buses would be provided priority if they were running later than the threshold. The purpose of this report is to investigate the effectiveness of TSP strategies on headway distributions, so as to ascertain whether or not TSP can be used to improve the distributions and provide more consistent service.

A brief review of literature will first be performed to recognize ways that TSP priority has been used to improve public transit services, particularly of BRT systems. A dataset provided by the Utah Transit Authority (UTA) of BRT timepoint data will then be cleaned, evaluated, and used to analyze the effects of TSP strategies on BRT headway distributions. After analysis is performed, conclusions and recommendations for future work will be provided.

