# Conclusions and Recommendations

A dataset of UVX arrival data was provided by Utah Transit Authority (UTA) to evaluate the effects of TSP on headways. The data was cleaned in order to remove outlying datapoints and create a useful dataset from which analysis of headway discrepancies could be used to evaluate the effectiveness of TSP thresholds on headway uniformity. Statistical analyses were performed on the dataset to verify what if any of the TSP thresholds are significant in achieving improved headway distributions.

This analysis has shown no evidence that TSP thresholds provide a significant effect on the headway distribution of buses belonging to the UVX BRT system when accounting for location and direction alone. This analysis only considers geospatial aspects of the dataset provided, and does not delve into analysis of geotemporal aspects of the BRT route such as time of day or dwell time. It is recommended that future analysis incorporating these parameters be performed, as it may yield more specific results of the effects of TSP on headway distributions.
