--- 
title: "UVX Headway Distribution"
author: "Logan Bennett"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is the book written for my 584R project."
---

# Abstract {-}


Bus Rapid Transit (BRT) systems make use of traffic signal prioritization and preemption (TSP) to increase system reliability, or the consistency with which these systems maintain established schedules. Studies have been done to determine the effects of prioritization on reliability, but less has been done to evaluate the effectiveness of changes to TSP on headway distributions. The UVX BRT system is a fairly new transit network in Utah County. This system makes use of signal prioritization not to maintain a set schedule of arrivals and departures, but rather to achieve consistent headways, or times between the arrivals of buses. What are the effects of variable signal prioritization to the headway distribution of this fleet of buses? Can altering signal priority timing affect the distribution of headway times, leading to more uniformity in arrivals? I plan to use a dataset of UVX arrival data provided by Utah Transit Authority (UTA) to evaluate the effects of signal priority on headways. I will then perform statistical analyses on the dataset to verify what if any of these changes are significant in achieving improved distributions.
